apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-alternativprodukter
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
  image: {{ image }}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
  openSearch:
    access: admin
    instance: grunndata
  kafka:
    pool: {{ kafka_cluster }}
  leaderElection: true
  env:
    - name: DB_DRIVER
      value: "org.postgresql.Driver"
    - name: RAPIDSANDRIVERS_ENABLED
      value: "{{ rapidsandrivers_enabled }}"
    - name: GRUNNDATA_DB_URL
      value: "http://hm-grunndata-db"
    - name: SCHEDULERS_ENABLED
      value: "{{ schedulers_enabled }}"
    - name: SWAGGER_ENABLED
      value: "{{ swagger_enabled }}"
    - name: SERVER_PORT
      value: "8080"
    - name: JDK_JAVA_OPTIONS
      value: "{{ java_opts }}"
    - name: OEBS_API_PROXY
      value: "{{ oebs_api_proxy }}"
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
  gcp:
    sqlInstances:
      - name: hm-grunndata-alternativprodukter-db
        type: POSTGRES_15
        tier: {{ disk_tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ disk_size }}
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: alternativprodukterdb
            envVarPrefix: DB
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: hm-grunndata-db
      external:
        - host: navikt.github.io
        - host: {{oebs_api_proxy}}
    inbound:
      rules:
        - application: hm-oversikt-frontend
        - application: hm-grunndata-index