apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: hm-grunndata-alternativprodukter
  namespace: teamdigihot
  labels:
    team: teamdigihot
spec:
  image: {{ image }}
  port: 8080
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  liveness:
    path: /internal/isAlive
    initialDelay: 20
  readiness:
    path: /internal/isReady
    initialDelay: 20
  replicas:
    min: {{ min_replicas }}
    max: {{ max_replicas }}
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1048Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: /internal/prometheus
  azure:
    application:
      enabled: true
  env:
    - name: DB_DRIVER
      value: "org.postgresql.Driver"
    - name: SCHEDULERS_ENABLED
      value: "{{ swagger_enabled }}"
    - name: SWAGGER_ENABLED
      value: "{{ schedulers_enabled }}"
    - name: SERVER_PORT
      value: "8080"
    - name: JAVA_OPTS
      value: "{{ java_opts }}"
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  gcp:
    sqlInstances:
      - name: hm-grunndata-alternativprodukter-db
        type: POSTGRES_14
        tier: {{ disk_tier }}
        diskType: SSD
        highAvailability: true
        diskSize: {{ disk_size }}
        diskAutoresize: true
        autoBackupHour: 3
        databases:
          - name: alternativprodukterdb
            envVarPrefix: DB
        cascadingDelete: false
  accessPolicy:
    outbound:
      external:
        - host: navikt.github.io
        - host: hm-oebs-api-proxy.dev-fss-pub.nais.io
    inbound:
      rules:
        - application: hm-oversikt-frontend