package no.nav.hm.grunndata.alternativprodukter.importing

enum class SubstituteFiles(val fileName: String) {
    V1_PERSONLOFTERE("V1_personloftere.xlsx"),
    V2_STOLER_MED_OPPREISINGSFUNKSJON("V2_stoler_med_oppreisingsfunksjon.xlsx"),
    V3_KALENDERE("V3_kalendere_1.xlsx"),
    V4_VARMEHJELPEMIDLER("V4_varmehjelpemidler.xlsx"),
    V5_ARBEIDSSTOLER("V5_arbeidsstoler.xlsx"),
    V6_SYN("V6_syn.xlsx"),
    V7_GANGHJELPEMIDLER("V7_ganghjelpemidler.xlsx"),
    V8_MANUELLE_RULLESTOLER_DK6("V8_manuelle_rullestoler_DK6.xlsx"),
    V9_ERS("V9_ers.xlsx"),
    V10_VOGNER("V10_vogner.xlsx"),
    V11_KJORERAMPER("V11_kjoreramper_2.xlsx"),
    V12_STAASTATIV_TRENINGS_AKTIVISERING("V12_staastativ_trenings_aktiviseringshjelpemidler.xlsx"),
    V13_SENGER("V13_senger.xlsx"),
    V14_KJOREPOSER("V14_kjoreposer_og_regncape.xlsx"),
    V15_MADRASSER("V15_madrasser.xlsx"),
    V16_MANUELLE_RULLESTOLER_DK9("V16_manuelle_rullestoler_DK9.xlsx"),
    V17_LOFTEPLATTFOMER_I_TRAPP("V17_lofteplattformer_og_hjelpemiddel_i_trapp.xlsx"),
    V18_SYKLER("V18_sykler.xlsx"),
    V19_HORSEL("V19_horsel.xlsx"),
    V20_KOMMUNIKASJON("V20_kommunikasjon.xlsx"),
    V21_SITTEMODULER("V21_sittemoduler.xlsx"),
}