name: Manually deploy to env
run-name: Deploy ${{ github.ref_name }} to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Deploy to environment
        default: 'dev'
        options:
          - dev

jobs:
  call-workflow:
    permissions:
      contents: write
      id-token: write
      packages: write
      security-events: write
      actions: read
    uses: navikt/mime-deploy/.github/workflows/build-deploy-dev-kotlin.yml@v0
    with:
      NAIS_RESOURCE: .nais/nais.yaml
      NAIS_VARS: ".nais/nais-dev.json"
      JAVA_VERSION: 17
      CODEQL_ENABLED: true
      SKIP_DRAFT_RELEASE: true
      DRAFTS_MAX: '100'
    secrets: inherit
